server:
  port: 8101

spring:
  application:
    name: authsrv

  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:30848}
        namespace: ${NACOS_NAMESPACE:}
      config:
        enabled: true
        server-addr: ${NACOS_SERVER_ADDR:localhost:30848}
        namespace: ${NACOS_NAMESPACE:}
        file-extension: yaml
        refresh-enabled: true

jwt:
  secret: ${JWT_SECRET:TizJwtSecretKey2026VeryLongSecretKeyForSecurity}
  access-token-expiration: 1800
  refresh-token-expiration: 604800
