apiVersion: v1
kind: ConfigMap
metadata:
  name: seata-config
  namespace: nexora-infra
data:
  registry.conf: |
    registry {
      type = "nacos"
      nacos {
        application = "seata-server"
        serverAddr = "nacos:8848"
        group = "SEATA_GROUP"
        namespace = ""
        cluster = "default"
        username = "nacos"
        password = "nacos"
      }
    }
    config {
      type = "nacos"
      nacos {
        serverAddr = "nacos:8848"
        namespace = ""
        group = "SEATA_GROUP"
        username = "nacos"
        password = "nacos"
        dataId = "seataServer.properties"
      }
    }
