apiVersion: v1
kind: Service
metadata:
  name: seata
  namespace: nexora-infra
  labels:
    app: seata
spec:
  type: ClusterIP
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: rpc
  - port: 7091
    targetPort: 7091
    protocol: TCP
    name: web
  selector:
    app: seata
