apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: nexora-infra
  labels:
    app: sentinel
spec:
  type: ClusterIP
  ports:
  - port: 8858
    targetPort: 8858
    protocol: TCP
    name: http
  selector:
    app: sentinel
