apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: nexora-infra
data:
  kibana.yml: |
    server.host: 0.0.0.0
    server.port: 5601
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    elasticsearch.username: elastic
    elasticsearch.password: Nexora@2026
    i18n.locale: zh-CN
