services:
  quizsrv:
    build:
      context: .
      args:
        PORT: 8105
    image: quizsrv:latest
    container_name: tiz-quizsrv
    restart: always
    ports:
      - "8105:8105"
    environment:
      - NACOS_SERVER_ADDR=${NACOS_SERVER_ADDR:-nacos:8080}
      - NACOS_NAMESPACE=${NACOS_NAMESPACE:-}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-Tiz@2026}
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-Tiz@2026}
    networks:
      - npass
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  npass:
    external: true
