apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: nexora-infra
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
      - name: nacos
        image: nacos/nacos-server:v3.1.1
        env:
        - name: MODE
          value: standalone
        - name: PREFER_HOST_MODE
          value: hostname
        - name: SPRING_DATASOURCE_PLATFORM
          value: mysql
        - name: MYSQL_SERVICE_HOST
          value: mysql
        - name: MYSQL_SERVICE_PORT
          value: "3306"
        - name: MYSQL_SERVICE_DB_NAME
          value: nacos
        - name: MYSQL_SERVICE_USER
          value: root
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_SERVICE_DB_PARAM
          value: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
        - name: NACOS_AUTH_ENABLE
          value: "true"
        - name: NACOS_AUTH_TOKEN
          value: SecretKey012345678901234567890123456789012345678901234567890123456789
        - name: NACOS_AUTH_IDENTITY_KEY
          value: serverIdentity
        - name: NACOS_AUTH_IDENTITY_VALUE
          value: security
        - name: JVM_XMS
          value: 512m
        - name: JVM_XMX
          value: 512m
        - name: JVM_XMN
          value: 256m
        ports:
        - containerPort: 8848
          name: http
        - containerPort: 9848
          name: gprc
        - containerPort: 9849
          name: api
        volumeMounts:
        - name: nacos-storage
          mountPath: /home/nacos/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /nacos/actuator/health
            port: 8848
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /nacos/actuator/health
            port: 8848
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: nacos-storage
        persistentVolumeClaim:
          claimName: nacos-pvc
