apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: nexora-infra
  labels:
    app: nacos
spec:
  type: ClusterIP
  ports:
  - port: 8848
    targetPort: 8848
    protocol: TCP
    name: http
  - port: 9848
    targetPort: 9848
    protocol: TCP
    name: gprc
  - port: 9849
    targetPort: 9849
    protocol: TCP
    name: api
  selector:
    app: nacos
