[workspace]
authors = ["suj1e <13156660820@163.com>"]
channels = ["conda-forge"]
name = "tizbot"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
dev = "uvicorn app.main:app --host 0.0.0.0 --port 40008 --reload"

[dependencies]
watchfiles = ">=0.20.0"
httptools = ">=0.6.0"
uvloop = ">=0.15.0"
langgraph = ">=1.0.9,<2"
fastapi = ">=0.131.0,<0.132"
uvicorn = ">=0.41.0,<0.42"
pydantic = ">=2.12.5,<3"
pydantic-settings = ">=2.13.1,<3"
python-dotenv = ">=1.2.1,<2"
httpx = ">=0.28.1,<0.29"
sse-starlette = ">=3.2.0,<4"
openai = ">=2.21.0,<3"
google-genai = ">=1.64.0,<2"
anthropic = ">=0.83.0,<0.84"
