apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: nexora-infra
type: Opaque
data:
  mysql-root-password: TGV4b3JhQDIwMjY=  # Nexora@2026
  mysql-password: TGV4b3JhQDIwMjY=       # Nexora@2026
