apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: nexora-infra
data:
  elasticsearch.yml: |
    cluster.name: nexora-cluster
    network.host: 0.0.0.0
    discovery.type: single-node
    bootstrap.memory_lock: true
    xpack.security.enabled: true
    xpack.security.enrollment.enabled: true
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
